name = "ohirume/tojson"
version = "0.2.2"
description = "Convert rbxm/rbxmx files to Argon model.json format"
license = "MIT"
authors = ["ohirume"]
repository = "https://github.com/0hirume/tojson"
includes = ["pesde.toml", "src/**", "bin/**", "README.md"]

[target]
environment = "lune"
lib = "src/init.luau"
bin = "bin/tojson.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
